
<div class="page-title">
  <div class="title_left">
    <h3><?php echo 'Sliders'; ?></h3>
  </div>
</div>
<div class="row">
  	<div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="x_panel">
	      	<div class="x_title">
	        	<h2><?php echo 'All Slider'; ?></h2>
	        	<div class="clearfix"></div>
	     	</div>
	      	<div class="x_content">
		        <table id="datatable" class="table table-striped table-bordered">
		          	<thead>
			          	<tr class="headings">
			          		<th class="hidden"> </th>
			                <th class="column-title"><?php echo __('Id');?> </th>
			                <th class="column-title"><?php echo __('Slider Name');?> </th>
			                <th class="column-title"><?php echo __('Title');?> </th>
			                <th class="column-title"><?php echo __('Detail');?> </th>
			                <th class="column-title"><?php echo __('Status');?> </th>
			                <th class="column-title"><?php echo __('Created At'); ?> </th>
			                <th class="column-title no-link last"><span class="nobr"><?php echo __('Action'); ?></span>
			                </th>
			                <th class="bulk-actions" colspan="7">
			                  <a class="antoo" style="color:#fff; font-weight:500;"><?php echo __('Bulk Actions');?> ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
			                </th>
			          	</tr>
			        </thead>
			        <tbody>
				         <?php //foreach ($this->getRating()->setOrder('rating_id', 'desc') as $key => $rating) { 
				         	?>
				         <tr>
				         	<td class="hidden"> </td>
				         	<td class=""><?php echo "1"; ?>  </td>
				         	<td class=""><?php echo "Slider 01"; ?>  </td>
				         	<td class=""><?php echo "Slider 01"; ?>  </td>
				         	<td class=""><?php echo "The first slider"; ?>  </td>
				         	<td class=""><?php echo "IsActive"; ?>  </td>
				         	<td class=""><?php echo "19/12/2017"; ?>  </td>
				         	<td class=" last"><a href="<?php echo $block->getUrl('#'); ?>"><?php echo __('View'); ?></a>
				         </tr>
				         <?php //} ?>
			        </tbody>    
		        </table>
	      	</div>
	    </div>  	
    </div>
 </div>

